name = "Laravel (Vue)"
comment = "Base scaffold for Laravel projects"
version = "1.1.0"

post_install_hook = [
    "docker compose up -d",
    "docker:laravel.test:composer install",
    "docker:laravel.test:npm install",
    "docker:laravel.test:php artisan key:generate",
    "docker:laravel.test:php artisan storage:link",
    "docker:laravel.test:npm run build",
    "docker:laravel.test:php artisan migrate",
    "docker compose down",
]

[hooks]
dev = ["docker compose up -d"]
stop = ["docker compose down"]

[[dependencies]]
name = "git"
check = "git --version"
install_hint = "https://git-scm.com/downloads"

[[dependencies]]
name = "docker"
check = "docker --version"
install_hint = "https://docs.docker.com/get-started/get-docker/"
