services:
    react-native-server:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './app/:/usr/src/app/app'
            - './assets/:/usr/src/app/assets'
            - './test/:/usr/src/app/test'
