services:
    next-server:
        build:
            context: './'
            dockerfile: ./docker/Dockerfile
        volumes:
            - './src/:/usr/src/app/src'
            - './public/:/usr/src/app/public'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            PORT: '80'
