name = "Next.js (Typescript)"
comment = "Base scaffold for Next.js projects"
version = "1.1.0"

post_install_hook = [
    "docker compose up -d",
    "docker compose down",
]

[hooks]
dev = ["docker compose up -d"]
stop = ["docker compose down"]

[[dependencies]]
name = "git"
check = "git --version"
install_hint = "https://git-scm.com/downloads"

[[dependencies]]
name = "docker"
check = "docker --version"
install_hint = "https://docs.docker.com/get-started/get-docker/"
